### PR TITLE
Added u2596-259F, added & modified nerd-dev (uE725-E729) Git icons…

### PR DESCRIPTION
**Pull request by cpkio**
+ u276D fix (wrong visual weight). Redrawn `nerd-dev-git` icons.

### CODE REVIEW

**Comment by slavfox** [comment]
Seems I accidentally invalidated this again trying to fix #50. I'll handle the conflicts when I have a moment, thanks.

**Comment by slavfox** [comment]
I was forced to revert this and your previous PR. For reasons unknown to me, and probably being the fault of FontForge being weird, all of the glyphs you contributed are broken under xterm. I could not find a cause nor reproduce the problem when making new glyphs, and I did not manage to fix the problematic glyphs. I would prefer to not have them rather than break the font partially.

What version of FontForge are you using? I'm on 20201107 on Arch.

**Comment by cpkio** [comment]
I'm using same version on Windows. Maybe I can commit individual glyphs in some way?

**Comment by slavfox** [comment]
The glyphs are still within the commit history of this repo, and I'll try to eventually incorporate them into the font. Unfortunately, despite being a text format, .sfd is effectively not hand-editable, so there's no way to commit the glyphs alone, especially without knowing why they were broken in the first place. I suspect Windows weirdness is at fault here, I work on Linux and have had PRs from another Linux user and this issue wasn't happening. Fonts are incredibly fickle cross-platform, sadly.

**Comment by cpkio** [comment]
The SFD file can be saved as directory with a bunch of `.glyph` and `.bitmap` files and opened as such, maybe that's a better way of managing this font. I'll see if I can install FontForge in a Linux VM.

**Comment by cpkio** [comment]
Trying to figure out wtf is going on
u2071 (ⁱ) glyph

## Windows FontForge
```
StartChar: uni2071
Encoding: 8305 8305 1877
Width: 1024
Flags: W
LayerCount: 2
EndChar
```

```
BDFChar: 1877 8305 6 2 2 4 8
J,k+MJ,fQL
```

## Manjaro FontForge

Drawn glyph from scratch on fresh repo clone. Git diff:
```
+StartChar: uni2071
+Encoding: 8305 8305 1862
+Width: 1024
+Flags: W
+LayerCount: 2
+EndChar
```
```
+BDFChar: 1862 8305 6 2 2 4 8
+J,k+MJ,fQL
```
Line endings didnt change either.

**Comment by slavfox** [comment]
I've rebooted, updated, reran fontforge on the previous commit, and it works now, but some other glyphs are broken. It seems to not be related to your PR after all, we were just unlucky that it was your glyphs specifically that broke. I'll debug a bit more, but it looks like you won't need to commit anything more, I'll revert to your patch once I get it working :D

**Comment by slavfox** [comment]
Your changes are now back on the master branch. I've modified the git symbols a bit to make them a bit lighter weight and more consistent with what arrows etc look like in the rest of the font.

Thank you so much for contributing, and apologies for all the trouble!

**Comment by cpkio** [comment]
This was useful after all. I've managed to install FF into Manjaro VM and built the fonts myself from my own fork just now, and everything seems to be working fine. Hopefully my font edits in Manjaro will be working for your builds too.

**Pull request merged**
